// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.google.services) apply false
    alias(libs.plugins.crashlytics) apply false
    alias(libs.plugins.firebase.perf) apply false
}

allprojects {
    configurations.all {
        resolutionStrategy.dependencySubstitution {
            def modules = [
                    'auto-register',
                    'auto-register-processor',
                    'adapter',
                    'adapter-processor',
                    'deeplink',
                    'deeplink-processor'
            ]
            modules.each { name ->
                if (findProject(":${name}") != null) {
                    substitute module("com.github.hoanganhtuan95ptit:${name}") using project(":${name}")
                }
            }
        }
    }
}
