pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        mavenLocal()
        maven { url 'https://jitpack.io' }
    }
}

rootProject.name = "RetirementLauncher"
include ':app'

def localPropertiesFile = new File(settings.rootDir, 'local.properties')
if (localPropertiesFile.exists()) {
    Properties properties = new Properties()
    localPropertiesFile.withInputStream { properties.load(it) }
    
    // Tự động include tất cả các properties bắt đầu bằng "module."
    properties.each { key, path ->
        if (key.startsWith("module.")) {
            def moduleName = key.substring("module.".length())
            def modulePath = new File(path.toString())
            
            if (modulePath.exists()) {
                include ":${moduleName}"
                project(":${moduleName}").projectDir = modulePath
            }
        }
    }
}
