pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        mavenLocal()
        maven { url 'https://jitpack.io' }
    }
}

rootProject.name = "RetirementLauncher"
include ':app'

// --- Logic Composite Build (includeBuild) ---

def localProperties = new Properties()
def localPropertiesFile = new File(settings.rootDir, 'local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withInputStream { localProperties.load(it) }
}

def rootProjects = [:] // Map<RootPath, List<ModuleName>>

localProperties.each { key, path ->
    if (key.startsWith("module.")) {
        def moduleName = key.substring("module.".length())
        if (moduleName == "config") return

        def moduleFile = new File(path.toString())
        if (moduleFile.exists()) {
            // Lấy thư mục cha làm Root Project (ví dụ: TProject, Adapter, Deeplink)
            def rootDir = moduleFile.parentFile.absolutePath
            if (!rootProjects.containsKey(rootDir)) {
                rootProjects[rootDir] = []
            }
            rootProjects[rootDir].add(moduleName)
        }
    }
}

// Thực hiện includeBuild cho từng Repo root
rootProjects.each { rootDir, modules ->
    includeBuild(rootDir) {
        dependencySubstitution {
            modules.each { name ->
                // Xác định group dựa trên project (TProject dùng .core, còn lại dùng group chung)
                def group = "com.github.hoanganhtuan95ptit"
                if (name == "node-engine" || name == "glide-loader") {
                    group = "com.github.hoanganhtuan95ptit.core"
                }
                
                substitute module("${group}:${name}") using project(":${name}")
            }
        }
    }
}
